import networkx as nx

# Dictionary that maps position names to position IDs and hierarchy number
# Key: position names (all possible in the dataset)
# Value: tuple of (Position ID, hierarchy number)
# This includes special teams related coaches.
position_id_mapping = {"head coach": ("HC","HC",1),
                        "head": ("HC", "HC", 1),
                        "interim head coach": ("iHC", "iHC", 1),
                        "offensive coordinator": ("OC", "OC", 2),
                        "passing game coordinator": ("OC", "OC", 2),
                        "run game coordinator": ("OC", "OC", 2),
                        "running game coordinator": ("OC", "OC", 2),
                        "passing game": ("OC", "OC", 2),
                        "pass game coordinator": ("OC", "OC", 2),
                        "pass offense coordinator": ("OC", "OC", 2),
                        "pass coordinator": ("OC", "OC", 2),
                        "passing coordinator": ("OC", "OC", 2),
                        "offensive passing game coordinator": ("OC", "OC", 2),
                        "special teams coordinator": ("SC", "SC", 2),
                        "defensive coordinator": ("DC", "DC", 2),
                        "defensive passing game coordinator": ("DC", "DC", 2),
                        "defensive pass game coordinator": ("DC", "DC", 2),
                        "pass defense coordinator": ("DC", "DC", 2),
                        "coverage coordinator": ("DC", "DC", 2),
                        "defensive front coordinator": ("DC", "DC", 2),
                        "run defense coordinator": ("DC", "DC", 2),
                        "quarterbacks": ("O", "QB", 3),
                        "quaterbacks": ("O", "QB", 3),
                        "running backs": ("O", "RB", 3),
                        "offensive line": ("O", "OL", 3),
                        "wide receivers": ("O", "WR", 3),
                        "wide receiverss": ("O", "WR", 3),
                        "receivers": ("O", "WR", 3),
                        "tight ends": ("O", "TE", 3),
                        "tights ends": ("O", "TE", 3),
                        "game management": ("O", "QB", 3),
                        "run game": ("O", "OL", 3),
                        "running game": ("O", "OL", 3),
                        "special teams": ("S", "S", 3),
                        "linebackers": ("D", "LB", 3),
                        "line": ("D", "LB", 3),
                        "defensive line": ("D", "DL", 3),
                        "secondary": ("D", "Sec", 3),
                        "pass rush": ("D", "DL", 3),
                        "defensive backs": ("D", "Sec", 3),
                        "defensive backfield": ("D", "Sec", 3),
                        "inside linebackers": ("D", "LB", 3),
                        "outside linebackers": ("D", "LB", 3),
                        "outisde linebackers": ("D", "LB", 3),
                        "cornerbacks": ("D", "Sec", 3),
                        "safeties": ("D", "Sec", 3),
                        "nickel backs": ("D", "Sec", 3),
                        "defensive nickel package": ("D", "Sec", 3),
                        "defensive ends": ("D", "DL", 3),
                        "defensive tackles": ("D", "DL", 3),
                        "defensive secondary": ("D", "Sec", 3)}

# this mapping only uses specific position names for position coaches:
# Offensive position coaches: quarterback, running backs, offensive line, wide receivers
# Deffensive position coaches: linebackers, defensive line, secondary
# Coordinaotrs: offensive/defensive coordinators
simple_position_id_mapping = {"head coach": ("HC", "HC", 1),
                        "head": ("HC", "HC", 1),
                        "interim head coach": ("iHC", "iHC", 1),
                        "offensive coordinator": ("OC", "OC", 2),
                        "passing game coordinator": ("OC", "OC", 2),
                        "run game coordinator": ("OC", "OC", 2),
                        "running game coordinator": ("OC", "OC", 2),
                        "passing game": ("OC", "OC", 2),
                        "pass game coordinator": ("OC", "OC", 2),
                        "pass offense coordinator": ("OC", "OC", 2),
                        "pass coordinator": ("OC", "OC", 2),
                        "passing coordinator": ("OC", "OC", 2),
                        "offensive passing game coordinator": ("OC", "OC", 2),
                        "defensive coordinator": ("DC", "DC", 2),
                        "defensive passing game coordinator": ("DC", "DC", 2),
                        "defensive pass game coordinator": ("DC", "DC", 2),
                        "pass defense coordinator": ("DC", "DC", 2),
                        "coverage coordinator": ("DC", "DC", 2),
                        "defensive front coordinator": ("DC", "DC", 2),
                        "run defense coordinator": ("DC", "DC", 2),
                        "quarterbacks": ("O", "QB", 3),
                        "quaterbacks": ("O", "QB", 3),
                        "game management": ("O", "QB", 3),
                        "running backs": ("O", "RB", 3),
                        "offensive line": ("O", "OL", 3),
                        "run game": ("O", "OL", 3),
                        "running game": ("O", "OL", 3),
                        "wide receivers": ("O", "WR", 3),
                        "wide receiverss": ("O", "WR", 3),
                        "receivers": ("O", "WR", 3),
                        "tight ends": ("O", "TE", 3),
                        "tights ends": ("O", "TE", 3),
                        "linebackers": ("D", "LB", 3),
                        "line": ("D", "LB", 3),
                        "inside linebackers": ("D", "LB", 3),
                        "outside linebackers": ("D", "LB", 3),
                        "outisde linebackers": ("D", "LB", 3),
                        "defensive line": ("D", "DL", 3),
                        "pass rush": ("D", "DL", 3),
                        "defensive ends": ("D", "DL", 3),
                        "defensive tackles": ("D", "DL", 3),
                        "secondary": ("D", "Sec", 3),
                        "defensive backs": ("D", "Sec", 3),
                        "defensive backfield": ("D", "Sec", 3),
                        "cornerbacks": ("D", "Sec", 3),
                        "safeties": ("D", "Sec", 3),
                        "nickel backs": ("D", "Sec", 3),
                        "defensive nickel package": ("D", "Sec", 3),
                        "defensive secondary": ("D", "Sec", 3)
                        }
